version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/miniBacktesting_be/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
#    - location: scripts/run_new_was.sh
#      timeout: 180
#      runas: ubuntu
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: ubuntu
#    - location: scripts/switch.sh
#      timeout: 180
#      runas: ubuntu
     - location: scripts/deploy.sh
#       timeout: 180
       timeout: 120
       runas: ec2-user
