version: "3"
services:
#  mysql:
#    image: mysql
#    environment:
#      MYSQL_DATABASE: minibacktesting
#      MYSQL_ROOT_PASSWORD: back20220302
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379

  springboot:
#    image: pyuseon/back_n_stock:version8
    build: .
    ports:
      - 80:8080
    depends_on:
#      - mysql
      - redis

